// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfnnlpysfomiyuloxqeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmbm5scHlzZm9taXl1bG94cWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjA3MDYsImV4cCI6MjA2MDEzNjcwNn0.MIEyCQPkF3ljqIA5UUjo-orpJJHDoIG0P_1lrYs8zUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);